apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-2
  labels:
    app: myapp-2
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
